apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: udagram
  labels:
    app: feed-backend
spec:
  selector:
    app: feed-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: udagram
  labels:
    app: feed-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-backend
  template:
    metadata:
      labels:
        app: feed-backend
    spec:
      containers:
      - name: feed-backend-container
        image: ybsnek/feed-api
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_HOST
          value: database-1.ctpfwg4b3n2v.eu-north-1.rds.amazonaws.com
        - name: POSTGRES_DB
          value: udagram
        - name: JWT_SECRET
          value: hello
        - name: URL
          value: http://localhost:4200
        - name: AWS_BUCKET
          value: udagram-ybsnek-dev
        - name: AWS_REGION
          value: eu-north-1
        - name: AWS_PROFILE
          value: default